<?php

namespace Database\Seeders;

use App\Models\SanPham;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SanPhamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sanPham = [
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick X Iron Spider-man Avengers End Game 1000% BB-SAEG",
                "Gia" => 131990000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-x-iron-spider-man-svengers-end-game-1000%-bb-saeg",
                "HinhAnh" => "Bearbrick-X-Iron-Spider-man-Avengers-End-Game-1000-BB-SAEG.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x ANNA SUI x M / mika ninagawa 1000% BB-ASMN",
                "Gia" => 49790000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-x-anna-sui-x-m-mika-ninagawa-1000%-bb-asmn",
                "HinhAnh" => "bearbrick-x-anna-sui-x-mika-ninagawa-1000-bb-asmn.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Peanuts Linus 400% BB-PL",
                "Gia" => 4890000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-peanuts-linus-400%-bb-pl",
                "HinhAnh" => "bearbrick-peanuts-linus-400-bb-pl-.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick NBA NY 400% &#038; 100% BB-NBA",
                "Gia" => 5190000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-nba-ny-400%",
                "HinhAnh" => "bearbrick-nba-ny-400-100-bb-nba.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Lucky Cat 100% &#038; 400% BB-LC14",
                "Gia" => 8390000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-lucky-cat-100%",
                "HinhAnh" => "bearbrick-lucky-cat-100-400-bb-lc14-2.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            //
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Pushead Silver 100% &amp; 400% Set BB-PL14",
                "Gia" => 12590000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-pushead-silver-100%",
                "HinhAnh" => "Bearbrick-Pushead-Silver-100-400-Set-BB-PL14.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Van Gogh Museum Courtesan 1000% BB-VGMC",
                "Gia" => 42390000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-van-gogh-museum-courtesan-1000%",
                "HinhAnh" => "bearbrick-van-gogh-museum-courtesan-1000-bb-vgmc-3.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Dylan&#8217;s Candy Bar 1000% BB-DCB",
                "Gia" => 48690000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-dylan&#8217",
                "HinhAnh" => "bearbrick-dylans-candy-bar-1000-bb-dcb.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Pushead Silver 1000% BB-PL",
                "Gia" => 34790000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-pushead-silver-1000%-bb-pl",
                "HinhAnh" => "bearbrick-pushead-silver-1000-bb-pl-1.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick atmos x WIND AND SEA 100% &amp; 400% Set BB-AWAS",
                "Gia" => 4790000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-atmos-x-wind-and-sea-100%",
                "HinhAnh" => "Bearbrick-atmos-x-WIND-AND-SEA-100-400-Set-BB-AWAS.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x Emotionally Unavailable Red Heart 100% &amp; 400% Set BB-EURH",
                "Gia" => 22980000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-x-emotionally-unavailable-red-heart-100%",
                "HinhAnh" => "Bearbrick-x-Emotionally-Unavailable-Red-Heart-100-amp-400-Set-BB-EURH.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" =>
                    "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Star Wars FN 2187 Stormtrooper 400% BB-SWFN2187",
                "Gia" => 9090000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-star-wars-fn-2187-stormtrooper-400%-bb-SWFN2187",
                "HinhAnh" => "Untitled-5.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Death Trooper Black 400% BB-DTB",
                "Gia" => 8090000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-death-trooper-black-400%-bb-dtb",
                "HinhAnh" => "Untitled-4.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick X-girl 2020 100% &amp; 400% Set BB-XGSET",
                "Gia" => 29590000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-x-girl-2020-100%",
                "HinhAnh" => "bearbrick_xgirl_2020_400_1609859764_4d8d2507_progressive.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "BEARBRICK MASTER-PIECE MPSC 100% &amp; 400% Set BB-MPI",
                "Gia" => 6690000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-master-piece-mpsc-100%",
                "HinhAnh" => "BEARBRICK-MASTER-PIECE-MPSC-100-400-Set-BB-MPI.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "BEARBRICK T-800 400%",
                "Gia" => 4790000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-t-800-400%",
                "HinhAnh" => "BEARBRICK-T-800-400.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "BEARBRICK NYABRICK HELLO KITTY 400%",
                "Gia" => 4690000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-nyabrick-hello-kitty-400%",
                "HinhAnh" => "BEARBRICK-NYABRICK-HELLO-KITTY-400.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Elvis Presley 400% &#038; 100% BB-EP",
                "Gia" => 5290000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản, về cơ bản những chú gấu Bearbrick xuất hiện rất đơn giản ở những cái nhìn đầu tiên, một bức tượng hình gấu bằng nhựa với nhiều kích cỡ và màu sắc khác nhau.",
                "Slug" => "bearbrick-elvis-presley-400%",
                "HinhAnh" => "bearbrick-elvis-presley-400-100-bb-ep-.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Boowy “No New York” 400% BB-BNNY",
                "Gia" => 4190000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick là gì đôi khi lại là câu hỏi đầu tiên của một tín đồ Be@rbrick tiềm năng. Được chế tác bởi Medicom Toy của Nhật Bản.",
                "Slug" => "bearbrick-boowy-no-new-york-400%",
                "HinhAnh" => "Bearbrick-Boowy-No-New-York-400-BB-BNNY-2.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Agent M (Men in Black : International) 400% BB-MIB",
                "Gia" => 5190000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản độc đáo của Men in Black.",
                "Slug" => "bearbrick-agent-m-men-in-black-400%",
                "HinhAnh" => "bearbrick-agent-m-men-in-black-international-400-bb-mib.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Guess Sport Jersey 100% & 400% BB-GSJ",
                "Gia" => 4190000.00,
                "SoLuong" => 10,
                "MoTa" => "Be@rbrick Guess phiên bản Sport Jersey.",
                "Slug" => "bearbrick-guess-sport-jersey-100%-400%",
                "HinhAnh" => "bearbrick-guess-sport-jersey-100-400-bb-gsj.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Pushead #5 100% & 400% Set ‘Gold’ BB-PG14",
                "Gia" => 20190000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Pushead #5 đặc biệt.",
                "Slug" => "bearbrick-pushead-5-100%-400%-gold",
                "HinhAnh" => "bearbrick-pushead-5-100-400-set-gold-bb-pg14.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Oasis White Chrome 1000% BB-OWC",
                "Gia" => 29190000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Oasis White Chrome sang trọng.",
                "Slug" => "bearbrick-oasis-white-chrome-1000%",
                "HinhAnh" => "bearbrick-oasis-white-chrome-1000-bb-owc.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Jean-Michel Basquiat #6 1000% BB-JMB6",
                "Gia" => 30590000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Basquiat độc quyền.",
                "Slug" => "bearbrick-jean-michel-basquiat-6-1000%",
                "HinhAnh" => "Bearbrick-Jean-Michel-Basquiat-6-1000-BB-JMB6.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Andy Warhol “Brillo” 1000% BB-AWB",
                "Gia" => 22790000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Andy Warhol ‘Brillo’.",
                "Slug" => "bearbrick-andy-warhol-brillo-1000%",
                "HinhAnh" => "Bearbrick-Andy-Warhol-Brillo-1000-BB-AWB.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick The Joker 1000% BB-TJ",
                "Gia" => 22990000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Bearbrick The Joker đặc biệt 1000%.",
                "Slug" => "bearbrick-the-joker-1000%",
                "HinhAnh" => "bearbrick-the-joker-1000-bb-tj-.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Jean-Michel Basquiat #7 1000% BB-JMB7",
                "Gia" => 25090000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Jean-Michel Basquiat #7 1000%.",
                "Slug" => "bearbrick-jean-michel-basquiat-7-1000%",
                "HinhAnh" => "Bearbrick-Jean-Michel-Basquiat-7-1000-BB-JMB7.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Anna Sui ‘Red & Beige’ 1000% BB-ASRB",
                "Gia" => 29190000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Anna Sui ‘Red & Beige’ tinh tế 1000%.",
                "Slug" => "bearbrick-anna-sui-red-beige-1000%",
                "HinhAnh" => "bearbrick-anna-sui-red-beige-1000-bb-asrb-.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick It’s 8:16! Coffee In a Cup of Tea 1000% BB-CCT",
                "Gia" => 22290000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản độc đáo: Coffee In a Cup of Tea 1000%.",
                "Slug" => "bearbrick-coffee-in-a-cup-of-tea-1000%",
                "HinhAnh" => "bearbrick-its-816-coffee-in-a-cup-of-tea-1000-bb-cct.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Medicom Toy Plus ‘Silver Chrome Ver’ 1000% BB-MTSC",
                "Gia" => 34790000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Medicom Toy Plus ‘Silver Chrome Ver’.",
                "Slug" => "bearbrick-medicom-toy-plus-silver-chrome-1000%",
                "HinhAnh" => "bearbrick-medicom-toy-plus-silver-chrome-ver-1000-bb-mtsc.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x Disney ‘Mickey Mouse’ (red/white) 1000% BB-DMM",
                "Gia" => 23690000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản đặc biệt Bearbrick x Disney ‘Mickey Mouse’ (red/white) 1000%.",
                "Slug" => "bearbrick-disney-mickey-mouse-red-white-1000%",
                "HinhAnh" => "Bearbrick-x-Disney-‘Mickey-Mouse-redwhite-1000-BB-DMM.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x Ghostbusters Stay Puft Marshmellow Man Angry Face 1000% BB-MMAF",
                "Gia" => 23690000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Ghostbusters Stay Puft Marshmellow Man Angry Face 1000%.",
                "Slug" => "bearbrick-ghostbusters-stay-puft-angry-face-1000%",
                "HinhAnh" => "bearbrick-x-ghostbusters-stay-puft-marshmellow-man-angry-face-1000-bb-mmaf.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick X Play Studio Akanobu Shinobu 1000% BB-PSAS",
                "Gia" => 23690000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản hợp tác Play Studio Akanobu Shinobu 1000%.",
                "Slug" => "bearbrick-play-studio-akanobu-shinobu-1000%",
                "HinhAnh" => "bearbrick-x-play-studio-akanobu-shinobu-1000-bb-psas.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Snoopy Belle 1000% (Peanuts) BB-SBP",
                "Gia" => 19490000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Snoopy Belle (Peanuts) đặc biệt 1000%.",
                "Slug" => "bearbrick-snoopy-belle-1000%",
                "HinhAnh" => "bearbrick-snoopy-belle-1000-peanuts-bb-sbp-1.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick X Atmos X Staple 1000% BB-AXS",
                "Gia" => 22290000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản hợp tác Atmos X Staple 1000%.",
                "Slug" => "bearbrick-atmos-staple-1000%",
                "HinhAnh" => "bearbrick-x-atmos-x-staple-1000-bb-axs.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x Atmos Elephant 1000% BB-ATEL",
                "Gia" => 23690000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản hợp tác Atmos Elephant 1000%.",
                "Slug" => "bearbrick-atmos-elephant-1000%",
                "HinhAnh" => "bearbrick-x-atmos-elephant-1000-bb-atel.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x Michael Jackson WEREWOLF 1000% BB-MJWW",
                "Gia" => 23690000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản hợp tác Michael Jackson WEREWOLF 1000%.",
                "Slug" => "bearbrick-michael-jackson-werewolf-1000%",
                "HinhAnh" => "bearbrick-x-michael-jackson-werewolf-1000-bb-mjww.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Punk Drunkers Tattoo Guy 1000% BB-PDTG",
                "Gia" => 17390000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Punk Drunkers Tattoo Guy 1000%.",
                "Slug" => "bearbrick-punk-drunkers-tattoo-guy-1000%",
                "HinhAnh" => "bearbrick-punk-drunkers-tattoo-guy-1000-bb-pdtg.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Misty ‘Black’ 1000% BB-MB",
                "Gia" => 23690000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Misty Black 1000%.",
                "Slug" => "bearbrick-misty-black-1000%",
                "HinhAnh" => "bearbrick-misty-black-1000-bb-mb.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x Star Wars Kylo Ren 1000% BB-SWKR",
                "Gia" => 18790000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản hợp tác Star Wars Kylo Ren 1000%.",
                "Slug" => "bearbrick-star-wars-kylo-ren-1000%",
                "HinhAnh" => "bearbrick-x-star-wars-kylo-ren-1000-bb-swkr.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x BAPE (R) Daruma 1000% BB-BRD",
                "Gia" => 52790000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản hợp tác BAPE (R) Daruma 1000%.",
                "Slug" => "bearbrick-bape-daruma-1000%",
                "HinhAnh" => "bearbrick-x-bape-daruma-1000-bb-brd-1.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x Atmos Animal Print 1000% BB-AAP",
                "Gia" => 25090000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản hợp tác Atmos Animal Print 1000%.",
                "Slug" => "bearbrick-atmos-animal-print-1000%",
                "HinhAnh" => "bearbrick-x-atmos-animal-print-1000-bb-aap.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick MARS 1000% BB-MARS",
                "Gia" => 76390000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản MARS 1000%.",
                "Slug" => "bearbrick-mars-1000%",
                "HinhAnh" => "bearbrick-mars-1000-bb-mars.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick X Disney Mickey Mouse Vintage 1000% BB-DMMV",
                "Gia" => 24390000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản hợp tác Disney Mickey Mouse Vintage 1000%.",
                "Slug" => "bearbrick-disney-mickey-mouse-vintage-1000%",
                "HinhAnh" => "bearbrick-x-disney-mickey-mouse-vintage-1000-bb-dmmv.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x Star Wars Darth Vader ‘Black’ 1000% BB-SWDV",
                "Gia" => 30590000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản hợp tác Star Wars Darth Vader Black 1000%.",
                "Slug" => "bearbrick-star-wars-darth-vader-black-1000%",
                "HinhAnh" => "Bearbrick-x-Star-Wars-Darth-Vader-‘Black-1000-BB-SWDV.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick The Beatles ‘Anthology’ BB-TBA",
                "Gia" => 30590000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản hợp tác The Beatles ‘Anthology’ 1000%.",
                "Slug" => "bearbrick-the-beatles-anthology-1000%",
                "HinhAnh" => "bearbrick-the-beatles-anthology-bb-tba.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Andy Warhol’s Elvis Presley 1000% BB-AWEP",
                "Gia" => 30590000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản hợp tác Andy Warhol’s Elvis Presley 1000%.",
                "Slug" => "bearbrick-andy-warhol-elvis-presley-1000%",
                "HinhAnh" => "bearbrick-andy-warhols-elvis-presley-1000-bb-awep.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Medicom Toy Plus 1000% ‘Gold Chrome’ BB-MTGC",
                "Gia" => 38890000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Medicom Toy Plus ‘Gold Chrome’ 1000%.",
                "Slug" => "bearbrick-medicom-toy-plus-gold-chrome-1000%",
                "HinhAnh" => "Bearbrick-Medicom-Toy-Plus-1000-‘Gold-Chrome-BB-MTGC.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Flying Balloons Girl 1000% BB-FBG",
                "Gia" => 27090000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Flying Balloons Girl 1000%.",
                "Slug" => "bearbrick-flying-balloons-girl-1000%",
                "HinhAnh" => "Bearbrick-Flying-Balloons-Girl-1000-BB-FBG-7.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick atmos BANDANA 100% & 400% Set of 2 BB-ABS2",
                "Gia" => 10090000.00,
                "SoLuong" => 10,
                "MoTa" => "Set sản phẩm atmos BANDANA 100% & 400%.",
                "Slug" => "bearbrick-atmos-bandana-100-400-set-2",
                "HinhAnh" => "Untitled_auto_x2-1.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x Marvel Captain America 400% BB-MCA",
                "Gia" => 23690000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản hợp tác Marvel Captain America 400%.",
                "Slug" => "bearbrick-marvel-captain-america-400%",
                "HinhAnh" => "Bearbrick-x-Marvel-Captain-America-400-BB-MCA.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Shoretrooper 400% BB-STMT",
                "Gia" => 9090000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Shoretrooper 400%.",
                "Slug" => "bearbrick-shoretrooper-400%",
                "HinhAnh" => "Bearbrick-Shoretrooper-400-BB-STMT.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Stormtrooper Chrome Ver. 400% BB-STCR",
                "Gia" => 9090000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản Stormtrooper Chrome Ver. 400%.",
                "Slug" => "bearbrick-stormtrooper-chrome-ver-400%",
                "HinhAnh" => "star-wars-medicom-toy-stormtrooper-bearbricks-01.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x Keith Haring x Disney Mickey Mouse 100% & 400% Set BB-KHDMM",
                "Gia" => 7290000.00,
                "SoLuong" => 10,
                "MoTa" => "Set sản phẩm Keith Haring x Disney Mickey Mouse 100% & 400%.",
                "Slug" => "bearbrick-keith-haring-disney-mickey-mouse-set-100-400%",
                "HinhAnh" => "mokhrdmm100400set-1.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Maneki Neko Peko-chan Black 100% & 400% Set BB-MNPB",
                "Gia" => 12690000.00,
                "SoLuong" => 10,
                "MoTa" => "Set sản phẩm Maneki Neko Peko-chan Black 100% & 400%.",
                "Slug" => "bearbrick-maneki-neko-peko-chan-black-set-100-400%",
                "HinhAnh" => "Untitled-3.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick MY FIRST BE@RBRICK Jester Ver. 100% & 400% Set BB-MFBBJ",
                "Gia" => 25090000.00,
                "SoLuong" => 10,
                "MoTa" => "Set MY FIRST BE@RBRICK Jester Ver. 100% & 400%.",
                "Slug" => "bearbrick-my-first-bearbrick-jester-ver-set-100-400%",
                "HinhAnh" => "Bearbrick-MY-FIRST-BE@RBRICK-Jester-Ver.-100-400-Set-BB-MFBBJ.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick 8:16! 100% & 400% Set BB-816",
                "Gia" => 6090000.00,
                "SoLuong" => 10,
                "MoTa" => "Set Bearbrick 8:16! 100% & 400%.",
                "Slug" => "bearbrick-816-set-100-400%",
                "HinhAnh" => "4-4.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x Xlarge x Hajime Sorayama Gold 100% & 400% Set BB-XHSG",
                "Gia" => 14590000.00,
                "SoLuong" => 10,
                "MoTa" => "Set hợp tác x Xlarge x Hajime Sorayama Gold 100% & 400%.",
                "Slug" => "bearbrick-xlarge-hajime-sorayama-gold-set-100-400%",
                "HinhAnh" => "xlarge_400_-08.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Maneki Neko Peko-chan Flurescent Pink 100% & 400% Set BB-MNPFP",
                "Gia" => 12490000.00,
                "SoLuong" => 10,
                "MoTa" => "Set Maneki Neko Peko-chan Flurescent Pink 100% & 400%.",
                "Slug" => "bearbrick-maneki-neko-peko-chan-flurescent-pink-100-400%",
                "HinhAnh" => "Bearbrick-Maneki-Neko-Peko-chan-Flurescent-Pink-100-400-Set-BB-MNPFP.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Maneki Neko Pekochan Flurescent Green 100% & 400% Set BB-MNPFP",
                "Gia" => 16490000.00,
                "SoLuong" => 10,
                "MoTa" => "Set Maneki Neko Peko-chan Flurescent Green 100% & 400%.",
                "Slug" => "bearbrick-maneki-neko-peko-chan-flurescent-green-100-400%",
                "HinhAnh" => "Bearbrick-Maneki-Neko-Pekochan-Flurescent-Green-100-400-Set-BB-MNPFP.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x MISHKA x LONG 400% BB-MLONG",
                "Gia" => 4590000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản hợp tác MISHKA x LONG 400%.",
                "Slug" => "bearbrick-mishka-long-400%",
                "HinhAnh" => "Bearbrick-x-MISHKA-x-LONG-400-BB-MLONG.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x Billionaire Boys Club x FDMTL 100% & 400% Set BB-BBCFDMTL",
                "Gia" => 8090000.00,
                "SoLuong" => 10,
                "MoTa" => "Set Bearbrick x Billionaire Boys Club x FDMTL 100% & 400%.",
                "Slug" => "bearbrick-bbcfdmtl-set-100-400%",
                "HinhAnh" => "billionaire-boys-club-fdmtl-team-up-for-a-medicom-toy-berbrick-01.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Shazam! 100% & 400% Set BB-SHAZ",
                "Gia" => 5690000.00,
                "SoLuong" => 10,
                "MoTa" => "Set Bearbrick Shazam! 100% & 400%.",
                "Slug" => "bearbrick-shazam-set-100-400%",
                "HinhAnh" => "Bearbrick-Shazam-100-400-Set-BB-SHAZ.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick x ANNA SUI x M / mika ninagawa 100% & 400% Set BB-ASMN",
                "Gia" => 10990000.00,
                "SoLuong" => 10,
                "MoTa" => "Set Bearbrick x ANNA SUI x M / mika ninagawa 100% & 400%.",
                "Slug" => "bearbrick-anna-sui-mika-ninagawa-set-100-400%",
                "HinhAnh" => "Bearbrick-x-ANNA-SUI-x-M-mika-ninagawa-100-amp-400-Set-BB-ASMN.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "BEARBRICK UNDERCOVER CERAMIC UFO 400% BB-UCUFO",
                "Gia" => 8490000.00,
                "SoLuong" => 10,
                "MoTa" => "Phiên bản BEARBRICK UNDERCOVER CERAMIC UFO 400%.",
                "Slug" => "bearbrick-undercover-ceramic-ufo-400%",
                "HinhAnh" => "BEARBRICK-UNDERCOVER-WHITE-BLUE-400-2.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "BEARBRICK CARNIVAL NO.2 100% & 400% Set BB-CAR",
                "Gia" => 7290000.00,
                "SoLuong" => 10,
                "MoTa" => "Set BEARBRICK CARNIVAL NO.2 100% & 400%.",
                "Slug" => "bearbrick-carnival-no2-set-100-400%",
                "HinhAnh" => "BEARBRICK-CARNIVAL-NO.2-100-amp-400-Set-BB-CAR.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "Bearbrick Keith Haring #5 100% & 400% Set BB-KH5",
                "Gia" => 6290000.00,
                "SoLuong" => 10,
                "MoTa" => "Set Bearbrick Keith Haring #5 100% & 400%.",
                "Slug" => "bearbrick-keith-haring-5-set-100-400%",
                "HinhAnh" => "be-at-rbrick-keith-haring-5-100-and-400_keith-haring_gallery_5e56f22127a29.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ],
            [
                "MaSP" => NULL,
                "TenSP" => "BEARBRICK FANTASIA MICKEY 100% & 400% Set BB-FTMK",
                "Gia" => 6590000.00,
                "SoLuong" => 10,
                "MoTa" => "Set BEARBRICK FANTASIA MICKEY 100% & 400%.",
                "Slug" => "bearbrick-fantasia-mickey-set-100-400%",
                "HinhAnh" => "BEARBRICK-FANTASIA-MICKEY-100-400-Set-BB-FTMK.jpg",
                "LoaiSP" => 1,
                "TrangThai" => 1,
                "created_at" => "2024-12-18 00:00:00",
                "updated_at" => "2024-12-18 00:00:00"
            ]
        ];
        foreach ($sanPham as $sp) {
            SanPham::factory()->create($sp);
        }
    }
}
